# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
include: [CNAME, tiny]
highlighter: pygments
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: DelightfulDev

url: http://www.delightfuldev.com
logo: "/assets/media/logo.png"
cover: "/assets/media/delightfuldev-facebook-cover.png"
title: DelightfulDev
description: Making Fun Apps
twitter: delightfuldev
email: nico@delightfuldev.com
author:
  name: Nico Prananta
  email: nico@delightfuldev.com
  twitter: nicnocquee
  bio: Making Apps

categories_path: categories.html
tags_path: tags.html

BASE_PATH:
