# Site settings
title: DelightfulDev
name: DelightfulDev
email: nico@delightfuldev.com
description: "Making Fun Apps"
info: "Made with &#x2764; by Nico Prananta from Kobe, Japan and Basel, Switzerland"
message: "Making fun apps."
keywords: "mac,apple,iphone,ios,osx,games,apps,development"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.delightfuldev.com" # the base hostname & protocol for your site
twitter_username: delightfuldev
author: Nico Prananta
# Build settings
markdown: kramdown
copyright: "&copy; 2014-2015 DelightfulDev by Nico Prananta"

facebook:
    image: /images/delightfuldev-facebook-cover.png
